# Numpy

## Iniciando

O numpy é uma biblioteca do python que trabalha com álgebra linear.

In [6]:
#Importando a bibliteca
import numpy as np


In [7]:
#Criando uma lista
lista = [1,2,3]
#Criando um array numpy daquela lista
np.array(lista)


array([1, 2, 3])

In [8]:
#Criando uma matriz
matriz = [[1,2,3],[4,5,6],[7,8,9]]
#Criando um array numpy daquela lista
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Um jeito simples de ver quantas dimencoes tem o array eh ver quantas chaves no comeco antes do primeiro item.

## Metodos

### Arange

Funciona de um jeito similar ao ja conhecido range, so que criando um array numpy com a lista.

In [11]:
np.arange(0, 10)
#obs: o ultimo numero nunca esta incluso.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Um terceiro parametro pode ser adicionado, ele diz a distancia entre os itens.
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

### Zeros


Dado um determinado tamanho, ele cria uma matriz so de zeros.

In [19]:
np.zeros(4)

array([0., 0., 0., 0.])

Caso voce queira criar uma matriz de duas dimensoes, basta passar uma tupla.

In [20]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones


Dado um determinado tamanho, ele cria uma matriz so de uns.


In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Eye

Dado um numero N, cria uma matriz identidade NxN.

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Linspace

Similar ao range, porem o ultimo atributo refera a quantos elementos serao mostrados igualmente espacados.

In [25]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [27]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Random


#### Rand


Similar ao random.rand do proprio python (pega N numeros aleatorios entre 0 e 1), mas devolvendo um array de numpy.

In [30]:
np.random.rand(5)


array([0.94990236, 0.02213854, 0.19179951, 0.11320063, 0.89534287])

obs: caso voce queira uma matriz de mais dimencoes basta adicionar uma virgula (nao precisa fazer como se fosse uma tupla).

#### Randn

Retorna numeros aleatorios, porem nao de uma distribuicao uniforme.

In [31]:
np.random.randn(5)


array([ 1.67998379,  0.37292788,  0.98904882, -0.90728456, -0.25460258])

#### Randint


Retorna numeros inteiros dentre um intervalo.


In [33]:
np.random.randint(0, 100, 3)

array([55, 49, 38])

In [35]:
#Macete pra conseguir uma lista de floats randomicos de 0 ate 100 sem casas decimais.
np.round(np.random.rand(3)*100, 0)

array([20., 64., 11.])

### Reshape

Dado uma matriz ou um vetor, transforma ele para um tamanho desejado.

In [38]:
arr = np.random.rand(25)
#array de 25 linhas.
arr

array([0.15283903, 0.74782548, 0.17037649, 0.44946358, 0.3665129 ,
       0.14078779, 0.74011927, 0.71522905, 0.91807064, 0.43407881,
       0.40656545, 0.4613594 , 0.62395804, 0.70746313, 0.57863073,
       0.58137853, 0.30406938, 0.93807708, 0.97071498, 0.48345777,
       0.7590358 , 0.70560929, 0.38764698, 0.80986135, 0.71104847])

In [40]:
arr = arr.reshape ((5, 5))
#Uma tupla eh passada como parametro, virando assim um vetor 5 por 5.
arr

array([[0.15283903, 0.74782548, 0.17037649, 0.44946358, 0.3665129 ],
       [0.14078779, 0.74011927, 0.71522905, 0.91807064, 0.43407881],
       [0.40656545, 0.4613594 , 0.62395804, 0.70746313, 0.57863073],
       [0.58137853, 0.30406938, 0.93807708, 0.97071498, 0.48345777],
       [0.7590358 , 0.70560929, 0.38764698, 0.80986135, 0.71104847]])

Voce pode checar qual o tamanho dos seus arrays utilizando o ATRIBUTO shape (nao eh um metodo, eh uma caracteristica).


In [41]:
arr.shape


(5, 5)

### Max e Min

Retorna o maior e o menor valor de um array.

In [48]:
arr.max()

0.9707149842077792

In [49]:
arr.min()

0.1407877883923876

### Argmax e Argmin

Retorna o indice do maior e menor valor do array.

In [50]:
arr.argmax()

18

In [51]:
arr.argmin()

5

## Indexacao e Fatiamento de arrays

A forma mais basica eh utilizando chaves, como se fosse uma lista.


In [69]:
np_array = np.arange(0, 30, 3)
np_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [55]:
np_array[3]

9

Voce tambem pode utilizar o conceito de slices ja conhecido em listas e strings python.

In [58]:
np_array[2:5]
#lembrando que o ultimo numero nao conta.

array([ 6,  9, 12])

In [60]:
np_array[:5]
#valores nao preenchidos seram 0 ou o max.

array([ 0,  3,  6,  9, 12])

In [62]:
np_array[2:-2]
#numeros negativos tambem.

array([ 6,  9, 12, 15, 18, 21])

In [63]:
np_array[ : :2]
#a distancia entre os itens tambem pode ser definida.

array([ 0,  6, 12, 18, 24])

In [71]:
np_array[2: ] = 100
np_array
#voce pode usar isso para alterar varios valores ao mesmo tempo.

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

### Em matrizes

In [122]:
np_mat = np.arange(50).reshape(5, 10)
np_mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

O primeiro couchetes faz referencia as linhas e utilizando virgulas as colunas.


In [123]:
np_mat [ :3] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [124]:
np_mat [:-2,2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

Um detalhe muito importante eh que quando voce cria um slice, voce cria uma refecia para aquele caminho. Caso um dos dois lados mude, ambos serao mudados.

In [125]:
np_mat2 = np_mat [:3]
np_mat2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [126]:
np_mat2 [:] = 100
np_mat2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [127]:
np_mat

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Uma forma de tratar isso eh utilizar o metodo copy.


In [128]:
np_mat3 = np_mat2[:2].copy()
np_mat3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [129]:
np_mat3 [:] = 50
np_mat3

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [130]:
np_mat2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Voce pode fazer os seus arrays passar por testes, como se fossem ifs.


In [132]:
np_mat > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

Isso retornara um array de booleanos do mesmo tamanho que o seu array.
Voce pode atribuir esse valor a uma variavel e usar como indice do array, para pegar apenas valores especificos.



In [133]:
bol = np_mat > 50
np_mat[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

Brincando um pouco...

In [138]:
brink = np.arange(0,100).reshape(10, 10)
brink

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
bol = brink % 3 == 0 
bol

array([[ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True]])

In [137]:
brink[bol]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## Operacoes

Voce tambem pode fazer operacoes (como soma, subtracao, multiplicacao, divisao, exponenciacao, etc) entre os seus arrays (os arrays tem que ter o mesmo tamanho) ou com numeros. Muito cuidado com a divisao, pois numeros nao podem ser divididos por zero, embora seu codigo nao seja parado por isso. 

In [145]:
brink2 = brink[:5,:4]
brink2

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [146]:
brink2 + brink2

array([[ 0,  2,  4,  6],
       [20, 22, 24, 26],
       [40, 42, 44, 46],
       [60, 62, 64, 66],
       [80, 82, 84, 86]])

In [147]:
brink2 + 100

array([[100, 101, 102, 103],
       [110, 111, 112, 113],
       [120, 121, 122, 123],
       [130, 131, 132, 133],
       [140, 141, 142, 143]])

In [148]:
brink2 / brink2

/usr/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [149]:
np.sqrt(brink2)
#raiz quadrada

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852]])

In [150]:
np.mean(brink2)
#media

21.5

In [152]:
np.std(brink2)
#padrao

14.186260959111108

In [ ]:
np.max(brink2)
#maximo

Qualquer duvida, so olhar a propria documentacao do numpy.